# Generated by Django 3.1.1 on 2020-09-11 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0003_auto_20200910_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_list',
            field=models.CharField(choices=[('0', 'admin'), ('1', 'user6')], default=0, max_length=255),
        ),
    ]
