# Generated by Django 3.1.1 on 2020-09-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0004_auto_20200911_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analytics',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='last_login',
            field=models.CharField(max_length=64, verbose_name='Last join or login'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='last_request',
            field=models.CharField(max_length=64, verbose_name='Last request (post or like)'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_list',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
