# Generated by Django 3.1.1 on 2020-09-13 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0005_auto_20200911_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
